
* Персональное рабочее окружение  ☮ λ ☯
** Фундаментальная база

- В основе /Персонального Рабочего Окружения/ интерпретатор классического диалекта /Лисп-2/.
- Динамическая природа языка позволяет менять  среду в интерактивном режиме;
- Это "/литературная программа/", которую может прочитать, понять и осознанно изменить любой пользователь, даже  малознакомый с языками программирования;
- /ПРО/ предоставляет удобный интерфейс пользователя для многочисленных компонентов Юникс, однако в виде приложения /ПРО/ может быть запущено и поверх ОС семейств /Windows/ или /MacOS/;

** Интегрированная среда

- Интерпретатор /Лисп/ является интерфейсом для прочих программ, вся мощность /Юникс/ доступна посредством высокоуровневого языка, но не заменяется им - в каждом отдельном случае используется инструмент, подходящий для конкретной задачи; 
- Дополнения  - /Моды/ расширяют функциональность среды, интегрируясь с возможности уже работающих инструментов, но не заменяют их. Эта философия принципиально отличается от распространённого в индустрии подхода (Windows/MacOS), когда для решения задач вы скачиваете и устанавливаете в систему новые бинарные «приложения», которые оказываются интегрированы между собой только через общесистемные сервисы, только одним определённым образом. /Моды/ же образуют симбиозы. К примеру, режим Управления Проектами интегрирован с режимом для работы с репозитариями GIT, а режим поддержки конкретного языка программирования использует инструменты анализа кода, общие для всех языков (LSP), а в режиме Телеграма работает перевод выделенного текста (`<C-c v>`)  и все нейросетевые функции... и везде работает Лисп! /Моды/  обеспечивают контекст;
- Во внешних Xorg приложениях поддерживаются универсальные клавиши навигации курсора, вставки из стека (C-y, M-y), переключения метода ввода (C-/) итп;

** Универсальное и гибкое управление окнами, вкладками и рабочими столами

- Один из /фреймов/ всегда на экране;
- На /фрейме/ одна или более /вкладок/, имя вкладки можно задать (s-r);
- Содержимое /вкладки/ может быть поделено на несколько /окон/, которыми можно управлять, и даже делать плавающими;
- В каждом /окне/ отображается какой-либо /буфер/ - это открытый файл или приложение, имя буфера можно задать (s-R), один буфер может отображаться в нескольких окнах;
- Конфигурацию фрейма, вкладок и окон можно «сохранить», чтобы вернуться;
- /Окна/ можно «откатить» к предыдущмм состояниям (`<s-u>/<s-U>`);

**  Программирование на всех языках

- Если язык программирования существует, то про это есть /Мод/;
- Протокол Языкового Сервера (LSP) добавляет современные инструменты работы с кодом;
- Протокол Дебаггера (DAP) обеспечивает  отладку всевозможных интерпретаторов;
- Подсказки по коду из разнообразных источников;
- Умное семантическое дополнение;  
- навигация по проектам;
- семантический и структурный анализ;
- генерация UML;
...  

** Организация

- Управление задачами;
- Заметки, Wiki, базы знаний;
- Учёт времени;
... 

** Интернет и коммуникация

- Встроеный браузер для безопасного просмотра нормальных HTML страниц;
- Удобный и многофункциональный почтовый клиент;
- Клиент новостных лент RSS, источники добавляются в простой org-файл
- Клиент IRC;
- Клиент Telegram с многооконностью и масштабированием текста;
- Интерфейсы для различных интернет-сервисов;
- Документация протокола HTTP
- Клиенты REST, GraphQL  
...

** Искусственный Интеллект

- Интерактивный буфер с нейросетью
- Перевод выбранного региона или слова, находящегося под курсором
- Поиск определения текущего слова
- Сводка для выбранного региона или текущего буфера
- Ревью кода 
- Изменение текста в выбранной области 
- Улучшение грамматики и орфографии 
- Улучшение формулировки 
- Упрощение и сокращение текста 
- Изменение выбранного кода
- улучшение выбранного кода 
- Завершение выбранного кода 
- Добавление нового кода на основе описания, сгенерированного с предоставленным контекстом.
- Преобразование выделенного текста 
- Создание списка из выбранной области
- Создание таблицы из выбранной области

** Проекты, репозитории

- Автоматическое определение проектов
- Быстрое переключение проектов
- Удобный процесс работы с GIT
- Поиск файлов или текста по проектам
- Контекст сборки проекта, привязаный терминал
    
... 

** Контейнеры и кластеры

- Просмотр запущенных контейнеров
- Просмотр журналов контейнера
- Подключение к оболочке в контейнере
  
** Простота и воспроизводимость

- Модульная организация;
- Сочетания клавиш в одной простой текстовой таблице ([[./сочетания-клавиш.org]]);
- Сценарии работы в системе расширяются благодаря /режимам/, /обработчикам/ и /перехватчикам/;
- Сохранение конфигураций рабочих окружений, окон и вкладок, мгновенное воспроизведение, когда они потребуются;

** Минимализм

- Цветовая тема в градациях серого, интенсивное использование типографики, рациональное использование цветов;
- /статус/ текущего /буфера/, часы и трей с иконками - всё это находится в /минибуфере/, пока тот неактивен;
 
** Хороший встроеный редактор

- Классический стиль комбинированных сочетаний с модальностью (Режим Бога);
