* Сделано
** ГОТОВО вкладки для рабочих столов
** ГОТОВО вкладки для терминалов
** ГОТОВО иконки для вкладок
** ГОТОВО иконки для приложений Xorg
** ГОТОВО Taoline: иконка мода
** ГОТОВО вкладки иконки
** ГОТОВО [#C] Добавить кнопки "назад" и "вперёд" на Toolbar (tab-bar-mode-history в итоге)
** ГОТОВО Перевод текста
** ГОТОВО outshine bullets не должны заменять каменты с пробелами от начала строк
** ГОТОВО Использовать early-init
** ГОТОВО Сделать оптимизации
** ГОТОВО Настройка Org mode в Tao-theme
** ГОТОВО Попробовать org modern
** ГОТОВО rainbow tags  
** ГОТОВО Прикрутить нейросеть (codeium)
** ГОТОВО [#A] Починить историю recentf
/Как-будто её сломал режим no-littering/
** ГОТОВО Добавить C-f1 как режим справки
** ГОТОВО Перевод дашборда
** ГОТОВО Кнопка для открытия минибуфера
** ГОТОВО [#A] История буферов в C-x b
** ГОТОВО [#B] Перевод файлов инициализации
** ГОТОВО Макрос для перевода символов
** ГОТОВО Рассмотреть использование синонимов
** ГОТОВО скриншоты одной кнопкой
** ГОТОВО Скриншот области
** ГОТОВО flymake во фрейме
** ГОТОВО Добавить проверку правописания на русском и английском
** ГОТОВО Установить словари Aspell
** ГОТОВО Настроить Flymake Aspell
** ГОТОВО C-d C-e должно удалять до конца строки, но не \n
** ГОТОВО flymake для emacs-lisp
** ГОТОВО Не понимает use-package?
** ГОТОВО Сделать справку для нового сниппета
** ГОТОВО добавить статус ДЕЛАЮ
** ГОТОВО Сделать перемещение на слово как в vi
** ГОТОВО [#A] Перетащить все кнопки в org-файл
** ГОТОВО [#B] Суммаризация новостей elfeed
** ГОТОВО [#B] Синхронизировать копипасту со стороны Xorg -   Когда в X11 приложении нажимается C-ins или S-del, текст должен сразу оказываться в истории копирования Emacs (повторное копирование в X11 добавляет текст в историю).
** ГОТОВО [#A] Выбор чата Telega с поиском (consult-telega-chat)
   Реализовать функциональность выбора чата в Telega с поддержкой поиска.

** ГОТОВО [#A] Yank from kill ring должен синхронизироваться с глобальным буфером
   Выбор из C-x y должен добавлять выбранное во все буферы.



** ГОТОВО Удаление до конца строки (C-d C-e) должно помещать удалённый текст в kill-ring и системный буфер обмена

* Программирование
** СДЕЛАТЬ [#A] Удобные клавиши для отладки - в первую очередь Emacs Lisp

** СДЕЛАТЬ [#B] автодополнение раздвигающее код (вместо попапа)
   Реализовать автодополнение, раздвигающее код.

** АНАЛИЗ [#B] NVM в Eshell
   Анализ и настройка работы NVM в Eshell.

** СДЕЛАТЬ M-. xref-find-definitions не работает когда все библиотеки скомпилированы в elc
   Найти и исправить проблему с xref-find-definitions.

* Управление задачами
** ДЕЛАЮ [#B] Сделать чтобы лента событий Jira и Confluence была доступна из agenda (C-c a)

** СДЕЛАТЬ [#B] Синхронизация org с Jira
   Настроить синхронизацию задач из Org-mode с системой Jira.

** СДЕЛАТЬ [#B] Если находишься не в проекте, то C-c c (capture) должна срабатывать глобально Реализация глобальной команды capture при отсутствии проекта.

** СДЕЛАТЬ [#B] Помидорка по удобным клавишам
   Добавить поддержку таймера "помидорка" с удобным набором клавиш.

** СДЕЛАТЬ [#B] ORG: Помидорка в taoline
   Показ таймера "помидорки" в taoline.

** СДЕЛАТЬ ORG: Синхронизация Org с телефоном
   Синхронизация задач и заметок Org-mode с мобильными устройствами.

** СДЕЛАТЬ ORG: Создавать события на дату по сочетанию кнопок
   Открывается календарь и событие добавляется в ЧТОДЕЛ.org.

** СДЕЛАТЬ ORG: Создавать повторяющиеся события
   Возможность создания повторяющихся событий в Org-mode.

** СДЕЛАТЬ ORG: Будильник (или голос) для сигнализации о событии
   Настроить звуковые уведомления для событий в Org-mode.

** СДЕЛАТЬ ORG: Предупреждение о событии заранее
   Настроить заранее уведомления о событиях в Org-mode.

** СДЕЛАТЬ ORG: Агенда должна собираться из СДЕЛАТЬ.org или ЧТОДЕЛ.org
   Собирать расписание и задачи из указанных файлов.

** СДЕЛАТЬ ORG: Настроить валидные пути для поиска org-файлов
   Настройка корректных путей для поиска org-файлов.

** СДЕЛАТЬ ORG: Просмотр Org файлов и Agenda в HTML (веб-сервер)

* Инструменты
** СДЕЛАТЬ [#B] Скринкасты одной кнопкой
   Реализовать функциональность для записи скринкастов нажатием одной кнопки.

** СДЕЛАТЬ [#C] Miro - Emacs
   Нарисовать интеграцию или взаимодействие Miro с Emacs.

** СДЕЛАТЬ https://github.com/leotaku/flycheck-aspell
   Настроить Flycheck для использования Aspell.
   
* ИИ
** СДЕЛАТЬ [#C] Распознавание речи
   Реализовать функциональность распознавания речи.

** СДЕЛАТЬ [#C] Голосовые команды
   Добавить поддержку голосовых команд.

** СДЕЛАТЬ [#C] Синтез речи
   Реализовать синтез речи в Emacs.

* Внешний вид
** СДЕЛАТЬ Внешний вид нотификаций
   Настроить внешний вид уведомлений.

** СДЕЛАТЬ В поиске показывать несколько строк вокруг найденной
   Показ нескольких строк контекста вокруг найденных результатов.

** СДЕЛАТЬ Фон Vterm сделать всегда чёрным
   Исправить фон Vterm, чтобы он всегда был черным. По какой-то причине :background не устанавливается и все цвета матчат тему.

** СДЕЛАТЬ [#C] Перевод меню в Magit
   Перевести интерфейс меню Magit.

** СДЕЛАТЬ [#C] Перевод и перемап функций, которые есть в C-c
   Перевод и переназначение функций, которые есть в C-c.

* Заголовок Мод: Tao-Head-Line
** СДЕЛАТЬ Путь в заголовке (tao-head-line)
   Показ пути в заголовке.

* Строка статуса: Taoline
** СДЕЛАТЬ [#B] Taoline: Иконка микрофона
   Добавить иконку микрофона в taoline.

** СДЕЛАТЬ [#B] В режиме Dired taoline должен показывать инфу по файлу, а для архивов показывать распакованный размер
   Улучшить отображение информации в taoline для Dired-режима, включая распакованный размер архивов.

* Техдолг
** СДЕЛАТЬ [#B] Заменить setq на customize-set-variable
   Переписать конфигурации с использованием `customize-set-variable` вместо `setq`.

** СДЕЛАТЬ Расположение монитора должно задаваться переменной *расположение-внешнего-монитора* (*'сверху* или *'справа*)
   Установить переменную для указания расположения внешнего монитора.

** АНАЛИЗ Отключить компиляцию
   Рассмотреть вопрос отключения компиляции исходников.

** АНАЛИЗ Telega конфликтует с transient
   internal-macroexpand-for-load: Eager macro-expansion failure: (error "transient-define-*: Interactive form missing")

* Разное
** СДЕЛАТЬ Переключать вкладки терминалов multi-vterm по Ctrl+1, Ctrl+2 итд.
   Настроить горячие клавиши для переключения вкладок терминалов.


