;; Минимальная тёмная тема для vterm
(deftheme vterm-dark-theme "Тёмная тема для буферов vterm")
(let ((class '((class color) (min-colors 89)))
      (fg "#e0e0e0")
      (bg "#181818")
      (comment "#606060")
      (cursor "#00e000")
      (red "#d75f5f")
      (green "#60b48a")
      (yellow "#ffd700")
      (blue "#62a0ea")
      (magenta "#c792ea")
      (cyan "#5fd7d7"))
  (custom-theme-set-faces
   'vterm-dark-theme
   `(default ((,class (:background ,bg :foreground ,fg))))
   `(cursor ((,class (:background ,cursor))))
   `(fringe ((,class (:background ,bg))))
   `(region ((,class (:background "#262a36"))))
   `(mode-line ((,class (:background "#222222" :foreground ,fg))))
   `(mode-line-inactive ((,class (:background "#222222" :foreground "#7c7c7c"))))
   `(minibuffer-prompt ((,class (:foreground ,blue))))
   `(font-lock-comment-face ((,class (:foreground ,comment :slant italic))))
   `(font-lock-string-face ((,class (:foreground ,cyan))))
   `(font-lock-keyword-face ((,class (:foreground ,magenta :weight bold))))
   `(font-lock-type-face ((,class (:foreground ,yellow))))
   `(font-lock-builtin-face ((,class (:foreground ,blue))))
   `(font-lock-variable-name-face ((,class (:foreground ,fg))))
   `(font-lock-function-name-face ((,class (:foreground ,green))))
   `(font-lock-warning-face ((,class (:foreground ,red :weight bold))))
   ;; vterm (~term-color faces)
   `(vterm-color-black ((,class (:foreground "#111111" :background "#1c1c1c"))))
   `(vterm-color-red ((,class (:foreground ,red :background ,red))))
   `(vterm-color-green ((,class (:foreground ,green :background ,green))))
   `(vterm-color-yellow ((,class (:foreground ,yellow :background ,yellow))))
   `(vterm-color-blue ((,class (:foreground ,blue :background ,blue))))
   `(vterm-color-magenta ((,class (:foreground ,magenta :background ,magenta))))
   `(vterm-color-cyan ((,class (:foreground ,cyan :background ,cyan))))
   `(vterm-color-white ((,class (:foreground "#e0e0e0" :background "#e0e0e0"))))
   ;; dim/inactive
   `(vterm-color-bright-black ((,class (:foreground "#303030" :background "#444444"))))
   `(vterm-color-bright-red ((,class (:foreground "#ff8787" :background "#af0000"))))
   `(vterm-color-bright-green ((,class (:foreground "#9aff87" :background "#5faf00"))))
   `(vterm-color-bright-yellow ((,class (:foreground "#ffffb0" :background "#afaf00"))))
   `(vterm-color-bright-blue ((,class (:foreground "#b0d7ff" :background "#005faf"))))
   `(vterm-color-bright-magenta ((,class (:foreground "#ffb0ff" :background "#8700af"))))
   `(vterm-color-bright-cyan ((,class (:foreground "#94ffff" :background "#00afaf"))))
   `(vterm-color-bright-white ((,class (:foreground "#ffffff" :background "#888888"))))
   ))
(provide-theme 'vterm-dark-theme)
