* Tasks

** СДЕЛАТЬ [#B] Если находишься не в проекте, то C-c c (capture) должна срабатывать глобально
   Реализация глобальной команды capture при отсутствии проекта.

** СДЕЛАТЬ [#A] Поддержавать имя TODO.org файла ЧТОДЕЛ.org

** ГОТОВО [#A] Выбор чата Telega с поиском (consult-telega-chat)
   Реализовать функциональность выбора чата в Telega с поддержкой поиска.

** СДЕЛАТЬ [#A] Yank from kill ring должен синхронизироваться с глобальным буфером
   Выбор из C-x y должен добавлять выбранное во все буферы.

** СДЕЛАТЬ [#B] Лента событий Jira и Confluence сохранялась в org-файл и была доступна из agenda (C-c a)
   Реализовать функциональность сохранения ленты событий из Jira и Confluence в org-файл, чтобы эти события были доступны из agenda с помощью команды C-c a.
```


** СДЕЛАТЬ [#B] Синхронизировать копипасту со стороны Xorg
   Когда в X11 приложении нажимается C-ins или S-del, текст должен сразу оказываться в истории копирования Emacs (повторное копирование в X11 добавляет текст в историю).

** СДЕЛАТЬ [#B] Taoline: Иконка микрофона
   Добавить иконку микрофона в taoline.

** СДЕЛАТЬ [#B] В режиме Dired taoline должен показывать инфу по файлу, а для архивов показывать распакованный размер
   Улучшить отображение информации в taoline для Dired-режима, включая распакованный размер архивов.

** СДЕЛАТЬ [#B] Скринкасты одной кнопкой
   Реализовать функциональность для записи скринкастов нажатием одной кнопки.

** СДЕЛАТЬ [#B] Синхронизация org с Jira
   Настроить синхронизацию задач из Org-mode с системой Jira.

** СДЕЛАТЬ [#B] ORG: Помидорка по удобным клавишам
   Добавить поддержку таймера "помидорка" с удобным набором клавиш.

** СДЕЛАТЬ [#B] ORG: Помидорка в taoline
   Показ таймера "помидорки" в taoline.

** СДЕЛАТЬ [#B] Заменить setq на customize-set-variable
   Переписать конфигурации с использованием `customize-set-variable` вместо `setq`.

** АНАЛИЗ [#B] NVM в Eshell
   Анализ и настройка работы NVM в Eshell.

** СДЕЛАТЬ Внешний вид нотификаций
   Настроить внешний вид уведомлений.

** СДЕЛАТЬ В поиске показывать несколько строк вокруг найденной
   Показ нескольких строк контекста вокруг найденных результатов.

** СДЕЛАТЬ Путь в заголовке (tao-head-line)
   Показ пути в заголовке.

** СДЕЛАТЬ автодополнение раздвигающее код (вместо попапа)
   Реализовать автодополнение, раздвигающее код.

** СДЕЛАТЬ https://github.com/leotaku/flycheck-aspell
   Настроить Flycheck для использования Aspell.

** СДЕЛАТЬ ORG: Синхронизация Org с телефоном
   Синхронизация задач и заметок Org-mode с мобильными устройствами.

** СДЕЛАТЬ ORG: Создавать события на дату по сочетанию кнопок
   Открывается календарь и событие добавляется в ЧТОДЕЛ.org.

** СДЕЛАТЬ ORG: Создавать повторяющиеся события
   Возможность создания повторяющихся событий в Org-mode.

** СДЕЛАТЬ ORG: Будильник (или голос) для сигнализации о событии
   Настроить звуковые уведомления для событий в Org-mode.

** СДЕЛАТЬ ORG: Предупреждение о событии заранее
   Настроить заранее уведомления о событиях в Org-mode.

** СДЕЛАТЬ ORG: Агенда должна собираться из СДЕЛАТЬ.org или ЧТОДЕЛ.org
   Собирать расписание и задачи из указанных файлов.

** СДЕЛАТЬ ORG: Настроить валидные пути для поиска org-файлов
   Настройка корректных путей для поиска org-файлов.

** СДЕЛАТЬ [#C] Распознавание речи
   Реализовать функциональность распознавания речи.

** СДЕЛАТЬ [#C] Голосовые команды
   Добавить поддержку голосовых команд.

** СДЕЛАТЬ [#C] Синтез речи
   Реализовать синтез речи в Emacs.

** СДЕЛАТЬ [#C] Перевод меню в Magit
   Перевести интерфейс меню Magit.

** СДЕЛАТЬ [#C] Перевод и перемап функций, которые есть в C-c
   Перевод и переназначение функций, которые есть в C-c.

** СДЕЛАТЬ [#C] Miro - Emacs
   Нарисовать интеграцию или взаимодействие Miro с Emacs.

** СДЕЛАТЬ Удаление до конца строки (C-d C-e) должно помещать удалённый текст в kill-ring и системный буфер обмена
   Реализовать эту функциональность для команд C-d и C-e.

** СДЕЛАТЬ Файл СДЕЛАТЬ.org должен выбираться из списка имён
   Реализовать возможность выбора файла СДЕЛАТЬ.org из предложенного списка.

** СДЕЛАТЬ Расположение монитора должно задаваться переменной *расположение-внешнего-монитора* (*'сверху* или *'справа*)
   Установить переменную для указания расположения внешнего монитора.

** СДЕЛАТЬ Переключать вкладки терминалов multi-vterm по Ctrl+1, Ctrl+2 итд.
   Настроить горячие клавиши для переключения вкладок терминалов.

** СДЕЛАТЬ Фон Vterm сделать всегда чёрным
   Исправить фон Vterm, чтобы он всегда был черным. По какой-то причине :background не устанавливается и все цвета матчат тему.

** СДЕЛАТЬ M-. xref-find-definitions не работает когда все библиотеки скомпилированы в elc
   Найти и исправить проблему с xref-find-definitions.

** АНАЛИЗ Отключить компиляцию
   Рассмотреть вопрос отключения компиляции исходников.

** АНАЛИЗ Не удалять el файлы после компиляции
   Рассмотреть вопрос, почему удаляются el файлы после компиляции и как это изменить.

*** АНАЛИЗ Почему они удаляются?
    Анализ причин удаления el файлов.

** АНАЛИЗ Telega конфликтует с transient
   internal-macroexpand-for-load: Eager macro-expansion failure: (error "transient-define-*: Interactive form missing")

